server:
  port: ${PORT:8080}
spring:
  application:
    name: plagiarism-detector-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://localhost:3306/${DB_NAME:plagiarism}
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER_NAME:totruongchinh@gmail.com}
    password: ${EMAIL_PASSWORD:kcbhtwgkghmnkvku}
    properties:
      mail:
        smtp:
          auth: true
      smtp:
        starttls:
          enable: true
        required: true
    from: ${EMAIL_FROM:totruongchinh@gmail.com}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /plagiarism-detector-server.html

openapi:
  service:
    api-docs: plagiarism-detector-server
    server: http://localhost:${server.port}
    title: Plagiarism Detector Document
    version: 1.0.0

plagiarism-search:
  host: ${PLAGIARISM_HOST:https://plagiarismsearch.com/api/v3}
  token: ${PLAGIARISM_EMAIL:totruongchinh@gmail.com}:${PLAGIARISM_TOKEN:iqsq17umPX5hJmqMleQSwLHpN6bW7Pdc4eWNLUuCMmwruUnv-214671387}


