server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root}
    url: jdbc:mysql://localhost:3306/plagiarism
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /plagiarism-detector-server.html

openapi:
  service:
    api-docs: plagiarism-detector-server
    server: http://localhost:${server.port}
    title: Plagiarism Detector Document
    version: 1.0.0

plagiarism-search:
  host: ${PLAGIARISM_HOST:https://plagiarismsearch.com/api/v3}
  token: ${PLAGIARISM_EMAIL:totruongchinh@gmail.com}:${PLAGIARISM_TOKEN:iqsq17umPX5hJmqMleQSwLHpN6bW7Pdc4eWNLUuCMmwruUnv-214671387}

jwt:
  secret-key: d29175cc8e31b7c3fc9d3d16562bb8495b9c6e90174f299cb59514d8f2fd56dc
  time-expired: 360000
